<a href="https://colab.research.google.com/github/ParthPathak27/Working-with-huge-matrices/blob/main/large_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 7
# Software Tools (CSP007P1M)
## Author: Parth Pathak (2020PCS1013)


### Here we will generate a random dense matrix of order 10K and perform the following computations:

*   Eigen Values

*   Eigen Vectors

*   Rank of Matrix

*   Inverse of Matix




In [ ]:
#Import the required libraries
import numpy as NP
from scipy import linalg as LA

Now we will generate the random dense matrix of order 10K

In [ ]:
A = NP.random.randint(0, 1000000, 100000000).reshape(10000, 10000)

In [ ]:
A

array([[266813, 890006, 565362, ..., 925799, 479472, 502536],
       [660829, 423396, 779827, ..., 437884,  37041, 484341],
       [240842, 955144, 446636, ..., 284699,  76166, 668475],
       ...,
       [642473, 853136,  22799, ..., 983562, 658998, 973683],
       [889509, 498489, 785399, ..., 272395, 714255,  83981],
       [605141, 759174, 812774, ..., 832034, 438975, 127777]])

We now will calculate it's eigen values and corresponding the eigen vectors using eig() method which takes the matrix as an input

In [ ]:
e_vals, e_vecs = LA.eig(A)

In [ ]:
print(e_vals)

[ 5.00015530e+09       +0.j          2.22364480e+07+18737520.61818405j
  2.22364480e+07-18737520.61818405j ... -2.26407501e+05  -306887.63584956j
 -1.15979275e+05       +0.j          2.34500439e+05       +0.j        ]


In [ ]:
print(e_vecs)

[[ 0.00988017+0.j         -0.00329969-0.0043201j  -0.00329969+0.0043201j
  ...  0.012172  -0.00330143j  0.00544875+0.j
  -0.01303829+0.j        ]
 [ 0.00998332+0.j          0.00047623-0.00701543j  0.00047623+0.00701543j
  ... -0.00943363+0.00726004j  0.00064274+0.j
  -0.00236675+0.j        ]
 [ 0.01003532+0.j          0.00228714-0.00125028j  0.00228714+0.00125028j
  ...  0.0081797 -0.00410054j  0.00337774+0.j
  -0.0032809 +0.j        ]
 ...
 [ 0.00996164+0.j          0.00583689-0.00281803j  0.00583689+0.00281803j
  ... -0.00799314+0.00211445j  0.00871272+0.j
   0.01476085+0.j        ]
 [ 0.01006311+0.j         -0.01407052-0.00544307j -0.01407052+0.00544307j
  ... -0.00439879-0.00534317j  0.01512484+0.j
  -0.00314076+0.j        ]
 [ 0.01005718+0.j          0.00174954+0.00370296j  0.00174954-0.00370296j
  ... -0.01209761+0.0091231j   0.01722685+0.j
   0.01334618+0.j        ]]


After calculating eigen values and corresponding eigen vectors of matrix, we now will compute it's rank using matrix_rank() method

In [ ]:
NP.linalg.matrix_rank(A)

10000

In [ ]:
(sign, logdet) = NP.linalg.slogdet(A)

If an array has a very small or very large determinant, then a call to det may overflow or underflow. This routine is more robust against such issues, because it computes the logarithm of the determinant rather than the determinant itself. It will Compute the sign and (natural) logarithm of the determinant of an array

In [ ]:
sign, logdet

(-1.0, 166787.26263788575)

As the determinant of matrix is nonzero it's invertible and we can compute it's inverse using inv() method

In [ ]:
A_inv = NP.linalg.inv(A)

In [ ]:
A_inv

array([[ 3.14353209e-08,  1.26704783e-07, -1.61463804e-07, ...,
         5.72613051e-08,  3.84093974e-08, -5.95913239e-09],
       [-1.82515342e-08, -6.52952656e-08,  1.17675524e-07, ...,
        -4.41216192e-08, -3.08159302e-08, -3.58589545e-09],
       [ 4.43828477e-08,  8.93967271e-08, -2.31152858e-07, ...,
         2.29633180e-08,  3.10946466e-08, -6.38651151e-08],
       ...,
       [-9.70635722e-09, -5.53745935e-08,  9.10369530e-08, ...,
        -1.06435700e-08, -3.78086499e-08,  1.13322397e-08],
       [ 1.05466744e-09,  2.15709344e-08,  2.90370396e-08, ...,
        -1.97155126e-10,  1.92683099e-09, -2.18945114e-09],
       [-4.33054740e-08, -5.48664509e-08,  1.99163752e-07, ...,
        -1.93001942e-08, -8.27397943e-08,  7.83259453e-08]])

### Now We will generate the random non-square matrix of order 9999 by 999 and will try to compute it's pseudo inverse

In [ ]:
B = NP.random.randn(9999, 999)

B is non-square matrix of order 9999 by 999

In [ ]:
B

array([[ 0.91536408,  0.04453584,  3.23245023, ...,  1.19416037,
         0.86780103, -0.5131803 ],
       [-0.67222387,  0.38964402,  0.93362178, ..., -0.43696912,
         0.9294176 , -1.56300554],
       [-2.00321757, -0.41119005,  0.1401192 , ...,  1.31344689,
        -0.08157576, -0.0063848 ],
       ...,
       [-2.54074946, -0.2225674 , -1.55710343, ..., -0.41612036,
         1.29384848, -0.69973097],
       [-1.36503618, -0.82021558,  0.5500444 , ..., -2.25231363,
         0.58924284, -0.21572682],
       [ 1.17321131,  0.81381791,  0.29275816, ..., -0.79713181,
         1.04237268,  0.12506286]])

Here we will use pinv() method to find the inverse of non-square matrix B

In [ ]:
B_inv = NP.linalg.pinv(B)

In [ ]:
B_inv

array([[ 1.03189304e-04, -6.76916225e-05, -1.85817409e-04, ...,
        -2.64124620e-04, -1.88635179e-04,  1.07182581e-04],
       [ 1.94091038e-05,  2.76676018e-05,  2.09576322e-05, ...,
         6.97033372e-06, -7.26873688e-05,  6.50542463e-05],
       [ 3.24368541e-04,  7.46403885e-05, -1.17120958e-05, ...,
        -1.58725670e-04,  9.23596523e-06, -3.83106000e-06],
       ...,
       [ 1.05810840e-04, -6.15802710e-05,  1.11055579e-04, ...,
        -2.48599252e-05, -2.15826741e-04, -4.55640443e-05],
       [ 1.16682721e-04,  6.84848377e-05,  2.73918683e-05, ...,
         1.85963711e-04,  8.51450403e-05,  1.03698036e-04],
       [-6.64179982e-05, -1.21424072e-04,  2.85756136e-05, ...,
        -6.53659287e-05, -3.58786329e-06,  9.58713244e-06]])